# Configuration for pr-watcher-notifier
"edx/*": &adr_config
  patterns:
    - "decisions/*.rst"
    - "decisions/*.md"
    - "*/decisions/*.rst"
    - "*/decisions/*.md"
    - "oeps/*.rst"
    - "oeps/*.md"
    - "guides/*.rst"
    - "guides/*.md"
    - "*/guides/*.rst"
    - "*/guides/*.md"
  recipients:
    # The Google Group for people who want email.
    # The #adr-notifications channel in the Open edX Slack.
    # "s5c2n2m2v2t0b2l2@openedx.slack.com" is on the ggroup.
    - "adr-notifications@googlegroups.com"
  subject: "Change in {{repo}}: {{pr.title}}"
  body: adr-body.txt
"openedx/*": *adr_config
