# Configuration for pr-watcher-notifier
"edx/*":
  exclude:
    - "edx/edx-documentation"
    - "edx/edx-developer-docs"
  patterns:
    - "*/*.rst"
    - "*/*.md"
  recipients:
    - "ned+notifier@edx.org"
    - "s5c2n2m2v2t0b2l2@openedx.slack.com"
  subject: "PR Watcher: change in {repo}"
  body: adr-body.txt
